#include "Protocol.h"

ROCKETMQ_NAMESPACE_BEGIN

#ifndef CLIENT_PROTOCOL_VERSION
#define CLIENT_PROTOCOL_VERSION "v1"
#endif

const char* Protocol::PROTOCOL_VERSION = CLIENT_PROTOCOL_VERSION;

ROCKETMQ_NAMESPACE_END